name: Deploy to Surge

on:
  push:
    branches:
      - main  # El workflow se ejecuta cuando haces push a la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2

      - name: Instalar Surge
        run: npm install --global surge

      - name: Desplegar a Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }} # usamos la API key guardada en GitHub Secrets
        run: |
          surge ./ https://david03bueno.surge.sh --token $SURGE_TOKEN
